### ISSUE TITLE
Integrate major and minor scales into to game

### ISSUE THREAD

**Issue by JohannesGrobelski** [JohannesGrobelski/PianoNotesTeacher#3]
# userstory
As a user i want to be able to train my note reading for the major (C, F and G Major) and minor (A and B Minor) scales in the
game. For that reason i can select chips that indicate if a note of a scale mentioned above is generated.

# content
Integrate models, display and note checking capabilities in the app to support the major (C, F and G Major) and minor (A and B Minor) scales in the game.

# tasks
- [x] Split NoteImageGenerator in 
   - [x] NoteGenerator with Capability to **generate** random notes in dependence of the scales
   - [x] NoteImageGenerator with Capability to **display** notes in dependence of the scales
- [x] Create a NoteChecker to validate a note played in dependence of the scales
- [x] Integrate NoteGenerator, NoteImageGenerator and NoteChecker in the app.
- [x] Add Chips scales: c major, f major, g major, a minor, b minor

# acceptance criteria
- [x] A user can select the chips connected to a scale mentioned above to select whether notes of this scale are displayed in the game.
